-- ItemSetDB: Era's armour sets, for the Collections window (MUI_Collections).
-- GENERATED by tools/itemsets_export.py from the client's ItemSet and item
-- tables - don't edit by hand.
--
-- set = { id, name, classes, level, quality, label, area?, skill?, faction?, items }
--   name      enUS; :GetName gives the client's own
--   classes   the classes it is for: bit (class id - 1) of each
--   level     the highest item level among its pieces
--   quality   the best quality among them
--   label     where it comes from, enUS; with it the area's id or the
--   area        profession's skill line when it is one the client can name
--   skill       (:GetSource)
--   faction   "Alliance" / "Horde" for a set only one side can earn
--   items     its pieces' item ids as worn, head to feet, jewellery last

object "ItemSetDB" {
    -- Every set, the highest item level first; those of one level by where
    -- they come from.
    GetSets = function(self)
        return self._sets
    end;

    GetSet = function(self, id)
        return self._byId[id]
    end;

    -- The sets an item is a piece of; nil when it is of none.
    GetSetsOfItem = function(self, itemId)
        return self._byItem[itemId]
    end;

    -- A set's name in the client's language.
    GetName = function(self, set)
        local name = C_Item.GetItemSetInfo(set.id)
        if name and name ~= "" then return name end
        return set.name
    end;

    -- Where a set comes from, in the client's language where it has the
    -- words, with the faction after a one-sided set's.
    GetSource = function(self, set)
        local source
        if set.area then
            source = C_Map.GetAreaInfo(set.area)
        elseif set.skill then
            source = C_TradeSkillUI.GetTradeSkillDisplayName(set.skill)
        end
        if not source or source == "" then source = set.label end
        if set.faction then
            source = source .. " (" .. (set.faction == "Alliance" and FACTION_ALLIANCE or FACTION_HORDE) .. ")"
        end
        return source
    end;

    __init = function(self)
        self._sets = {
            { id = 524, name = "Bonescythe Armor", classes = 8, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22478, 22479, 22476, 22483, 22481, 22482, 22477, 22480, 23060 } },
            { id = 530, name = "Cryptstalker Armor", classes = 4, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22438, 22439, 22436, 22443, 22441, 22442, 22437, 22440, 23067 } },
            { id = 523, name = "Dreadnaught's Battlegear", classes = 1, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22418, 22419, 22416, 22423, 22421, 22422, 22417, 22420, 23059 } },
            { id = 521, name = "Dreamwalker Raiment", classes = 1024, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22490, 22491, 22488, 22495, 22493, 22494, 22489, 22492, 23064 } },
            { id = 526, name = "Frostfire Regalia", classes = 128, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22498, 22499, 22496, 22503, 22501, 22502, 22497, 22500, 23062 } },
            { id = 529, name = "Plagueheart Raiment", classes = 256, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22506, 22507, 22504, 22511, 22509, 22510, 22505, 22508, 23063 } },
            { id = 528, name = "Redemption Armor", classes = 2, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22428, 22429, 22425, 22424, 22426, 22431, 22427, 22430, 23066 } },
            { id = 527, name = "The Earthshatterer", classes = 64, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22466, 22467, 22464, 22471, 22469, 22470, 22465, 22468, 23065 } },
            { id = 525, name = "Vestments of Faith", classes = 16, level = 92, quality = 4, label = "Naxxramas", area = 3456,
              items = { 22514, 22515, 22512, 22519, 22517, 22518, 22513, 22516, 23061 } },
            { id = 505, name = "Avenger's Battlegear", classes = 2, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21387, 21391, 21389, 21390, 21388 } },
            { id = 496, name = "Conqueror's Battlegear", classes = 1, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21329, 21330, 21331, 21332, 21333 } },
            { id = 497, name = "Deathdealer's Embrace", classes = 8, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21360, 21361, 21364, 21362, 21359 } },
            { id = 499, name = "Doomcaller's Attire", classes = 256, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21337, 21335, 21334, 21336, 21338 } },
            { id = 503, name = "Enigma Vestments", classes = 128, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21347, 21345, 21343, 21346, 21344 } },
            { id = 507, name = "Garments of the Oracle", classes = 16, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21348, 21350, 21351, 21352, 21349 } },
            { id = 493, name = "Genesis Raiment", classes = 1024, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21353, 21354, 21357, 21356, 21355 } },
            { id = 501, name = "Stormcaller's Garb", classes = 64, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21372, 21376, 21374, 21375, 21373 } },
            { id = 509, name = "Striker's Garb", classes = 4, level = 88, quality = 4, label = "Ahn'Qiraj", area = 3428,
              items = { 21366, 21367, 21370, 21368, 21365 } },
            { id = 218, name = "Battlegear of Wrath", classes = 1, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16963, 16961, 16966, 16959, 16964, 16960, 16962, 16965 } },
            { id = 213, name = "Bloodfang Armor", classes = 8, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16908, 16832, 16905, 16911, 16907, 16910, 16909, 16906 } },
            { id = 215, name = "Dragonstalker Armor", classes = 4, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16939, 16937, 16942, 16935, 16940, 16936, 16938, 16941 } },
            { id = 217, name = "Judgement Armor", classes = 2, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16955, 16953, 16958, 16951, 16956, 16952, 16954, 16957 } },
            { id = 212, name = "Nemesis Raiment", classes = 256, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16929, 16932, 16931, 16934, 16928, 16933, 16930, 16927 } },
            { id = 210, name = "Netherwind Regalia", classes = 128, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16914, 16917, 16916, 16918, 16913, 16818, 16915, 16912 } },
            { id = 214, name = "Stormrage Raiment", classes = 1024, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16900, 16902, 16897, 16904, 16899, 16903, 16901, 16898 } },
            { id = 216, name = "The Ten Storms", classes = 64, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16947, 16945, 16950, 16943, 16948, 16944, 16946, 16949 } },
            { id = 211, name = "Vestments of Transcendence", classes = 16, level = 76, quality = 4, label = "Blackwing Lair", area = 2677,
              items = { 16921, 16924, 16923, 16926, 16920, 16925, 16922, 16919 } },
            { id = 402, name = "Field Marshal's Aegis", classes = 2, level = 74, quality = 4, label = "PvP Rank 13", faction = "Alliance",
              items = { 16474, 16476, 16473, 16471, 16475, 16472 } },
            { id = 384, name = "Field Marshal's Battlegear", classes = 1, level = 74, quality = 4, label = "PvP Rank 13", faction = "Alliance",
              items = { 16478, 16480, 16477, 16484, 16479, 16483 } },
            { id = 395, name = "Field Marshal's Pursuit", classes = 4, level = 74, quality = 4, label = "PvP Rank 13", faction = "Alliance",
              items = { 16465, 16468, 16466, 16463, 16467, 16462 } },
            { id = 389, name = "Field Marshal's Raiment", classes = 16, level = 74, quality = 4, label = "PvP Rank 13", faction = "Alliance",
              items = { 17602, 17604, 17605, 17608, 17603, 17607 } },
            { id = 388, name = "Field Marshal's Regalia", classes = 128, level = 74, quality = 4, label = "PvP Rank 13", faction = "Alliance",
              items = { 16441, 16444, 16443, 16440, 16442, 16437 } },
            { id = 397, name = "Field Marshal's Sanctuary", classes = 1024, level = 74, quality = 4, label = "PvP Rank 13", faction = "Alliance",
              items = { 16451, 16449, 16452, 16448, 16450, 16459 } },
            { id = 392, name = "Field Marshal's Threads", classes = 256, level = 74, quality = 4, label = "PvP Rank 13", faction = "Alliance",
              items = { 17578, 17580, 17581, 17584, 17579, 17583 } },
            { id = 394, name = "Field Marshal's Vestments", classes = 8, level = 74, quality = 4, label = "PvP Rank 13", faction = "Alliance",
              items = { 16455, 16457, 16453, 16454, 16456, 16446 } },
            { id = 383, name = "Warlord's Battlegear", classes = 1, level = 74, quality = 4, label = "PvP Rank 13", faction = "Horde",
              items = { 16542, 16544, 16541, 16548, 16543, 16545 } },
            { id = 386, name = "Warlord's Earthshaker", classes = 64, level = 74, quality = 4, label = "PvP Rank 13", faction = "Horde",
              items = { 16578, 16580, 16577, 16574, 16579, 16573 } },
            { id = 396, name = "Warlord's Pursuit", classes = 4, level = 74, quality = 4, label = "PvP Rank 13", faction = "Horde",
              items = { 16566, 16568, 16565, 16571, 16567, 16569 } },
            { id = 390, name = "Warlord's Raiment", classes = 16, level = 74, quality = 4, label = "PvP Rank 13", faction = "Horde",
              items = { 17623, 17622, 17624, 17620, 17625, 17618 } },
            { id = 387, name = "Warlord's Regalia", classes = 128, level = 74, quality = 4, label = "PvP Rank 13", faction = "Horde",
              items = { 16533, 16536, 16535, 16540, 16534, 16539 } },
            { id = 398, name = "Warlord's Sanctuary", classes = 1024, level = 74, quality = 4, label = "PvP Rank 13", faction = "Horde",
              items = { 16550, 16551, 16549, 16555, 16552, 16554 } },
            { id = 391, name = "Warlord's Threads", classes = 256, level = 74, quality = 4, label = "PvP Rank 13", faction = "Horde",
              items = { 17591, 17590, 17592, 17588, 17593, 17586 } },
            { id = 393, name = "Warlord's Vestments", classes = 8, level = 74, quality = 4, label = "PvP Rank 13", faction = "Horde",
              items = { 16561, 16562, 16563, 16560, 16564, 16558 } },
            { id = 546, name = "Lieutenant Commander's Arcanum", classes = 128, level = 71, quality = 3, label = "PvP Rank 10", faction = "Alliance",
              items = { 23318, 23319, 23305, 23290, 23304, 23291 } },
            { id = 545, name = "Lieutenant Commander's Battlearmor", classes = 1, level = 71, quality = 3, label = "PvP Rank 10", faction = "Alliance",
              items = { 23314, 23315, 23300, 23286, 23301, 23287 } },
            { id = 547, name = "Lieutenant Commander's Dreadgear", classes = 256, level = 71, quality = 3, label = "PvP Rank 10", faction = "Alliance",
              items = { 23310, 23311, 23297, 23282, 23296, 23283 } },
            { id = 548, name = "Lieutenant Commander's Guard", classes = 8, level = 71, quality = 3, label = "PvP Rank 10", faction = "Alliance",
              items = { 23312, 23313, 23298, 23284, 23299, 23285 } },
            { id = 549, name = "Lieutenant Commander's Investiture", classes = 16, level = 71, quality = 3, label = "PvP Rank 10", faction = "Alliance",
              items = { 23316, 23317, 23303, 23288, 23302, 23289 } },
            { id = 550, name = "Lieutenant Commander's Pursuance", classes = 4, level = 71, quality = 3, label = "PvP Rank 10", faction = "Alliance",
              items = { 23306, 23307, 23292, 23279, 23293, 23278 } },
            { id = 544, name = "Lieutenant Commander's Redoubt", classes = 2, level = 71, quality = 3, label = "PvP Rank 10", faction = "Alliance",
              items = { 23276, 23277, 23272, 23274, 23273, 23275 } },
            { id = 551, name = "Lieutenant Commander's Refuge", classes = 1024, level = 71, quality = 3, label = "PvP Rank 10", faction = "Alliance",
              items = { 23308, 23309, 23294, 23280, 23295, 23281 } },
            { id = 542, name = "Champion's Arcanum", classes = 128, level = 71, quality = 3, label = "PvP Rank 10", faction = "Horde",
              items = { 23263, 23264, 22886, 22870, 22883, 22860 } },
            { id = 537, name = "Champion's Battlearmor", classes = 1, level = 71, quality = 3, label = "PvP Rank 10", faction = "Horde",
              items = { 23244, 23243, 22872, 22868, 22873, 22858 } },
            { id = 541, name = "Champion's Dreadgear", classes = 256, level = 71, quality = 3, label = "PvP Rank 10", faction = "Horde",
              items = { 23255, 23256, 22884, 22865, 22881, 22855 } },
            { id = 522, name = "Champion's Guard", classes = 8, level = 71, quality = 3, label = "PvP Rank 10", faction = "Horde",
              items = { 23257, 23258, 22879, 22864, 22880, 22856 } },
            { id = 540, name = "Champion's Investiture", classes = 16, level = 71, quality = 3, label = "PvP Rank 10", faction = "Horde",
              items = { 23261, 23262, 22885, 22869, 22882, 22859 } },
            { id = 543, name = "Champion's Pursuance", classes = 4, level = 71, quality = 3, label = "PvP Rank 10", faction = "Horde",
              items = { 23251, 23252, 22874, 22862, 22875, 22843 } },
            { id = 539, name = "Champion's Refuge", classes = 1024, level = 71, quality = 3, label = "PvP Rank 10", faction = "Horde",
              items = { 23253, 23254, 22877, 22863, 22878, 22852 } },
            { id = 538, name = "Champion's Stormcaller", classes = 64, level = 71, quality = 3, label = "PvP Rank 10", faction = "Horde",
              items = { 23259, 23260, 22876, 22867, 22887, 22857 } },
            { id = 480, name = "Confessor's Raiment", classes = 16, level = 68, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19841, 19843, 19842, 19594, 19958 } },
            { id = 477, name = "Predator's Armor", classes = 4, level = 68, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19831, 19833, 19832, 19621, 19953 } },
            { id = 511, name = "Battlegear of Heroism", classes = 1, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 21999, 22001, 21997, 21996, 21998, 21994, 22000, 21995 } },
            { id = 515, name = "Beastmaster Armor", classes = 4, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 22013, 22016, 22060, 22011, 22015, 22010, 22017, 22061 } },
            { id = 512, name = "Darkmantle Armor", classes = 8, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 22005, 22008, 22009, 22004, 22006, 22002, 22007, 22003 } },
            { id = 518, name = "Deathmist Raiment", classes = 256, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 22074, 22073, 22075, 22071, 22077, 22070, 22072, 22076 } },
            { id = 513, name = "Feralheart Raiment", classes = 1024, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 22109, 22112, 22113, 22108, 22110, 22106, 22111, 22107 } },
            { id = 517, name = "Sorcerer's Regalia", classes = 128, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 22065, 22068, 22069, 22063, 22066, 22062, 22067, 22064 } },
            { id = 516, name = "Soulforge Armor", classes = 2, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 22091, 22093, 22089, 22088, 22090, 22086, 22092, 22087 } },
            { id = 519, name = "The Five Thunders", classes = 64, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 22097, 22101, 22102, 22095, 22099, 22098, 22100, 22096 } },
            { id = 514, name = "Vestments of the Virtuous", classes = 16, level = 66, quality = 4, label = "Dungeon Set 2",
              items = { 22080, 22082, 22083, 22079, 22081, 22078, 22085, 22084 } },
            { id = 201, name = "Arcanist Regalia", classes = 128, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16795, 16797, 16798, 16799, 16801, 16802, 16796, 16800 } },
            { id = 209, name = "Battlegear of Might", classes = 1, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16866, 16868, 16865, 16861, 16863, 16864, 16867, 16862 } },
            { id = 205, name = "Cenarion Raiment", classes = 1024, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16834, 16836, 16833, 16830, 16831, 16828, 16835, 16829 } },
            { id = 203, name = "Felheart Raiment", classes = 256, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16808, 16807, 16809, 16804, 16805, 16806, 16810, 16803 } },
            { id = 206, name = "Giantstalker Armor", classes = 4, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16846, 16848, 16845, 16850, 16852, 16851, 16847, 16849 } },
            { id = 208, name = "Lawbringer Armor", classes = 2, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16854, 16856, 16853, 16857, 16860, 16858, 16855, 16859 } },
            { id = 204, name = "Nightslayer Armor", classes = 8, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16821, 16823, 16820, 16825, 16826, 16827, 16822, 16824 } },
            { id = 207, name = "The Earthfury", classes = 64, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16842, 16844, 16841, 16840, 16839, 16838, 16843, 16837 } },
            { id = 202, name = "Vestments of Prophecy", classes = 16, level = 66, quality = 4, label = "Molten Core", area = 2717,
              items = { 16813, 16816, 16815, 16819, 16812, 16817, 16814, 16811 } },
            { id = 469, name = "The Highlander's Determination", classes = 68, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Alliance",
              items = { 20055, 20043, 20050 } },
            { id = 470, name = "The Highlander's Fortitude", classes = 68, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Alliance",
              items = { 20056, 20044, 20051 } },
            { id = 473, name = "The Highlander's Intent", classes = 400, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Alliance",
              items = { 20061, 20047, 20054 } },
            { id = 471, name = "The Highlander's Purpose", classes = 1032, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Alliance",
              items = { 20059, 20045, 20052 } },
            { id = 467, name = "The Highlander's Resolution", classes = 3, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Alliance",
              items = { 20057, 20041, 20048 } },
            { id = 468, name = "The Highlander's Resolve", classes = 3, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Alliance",
              items = { 20058, 20042, 20049 } },
            { id = 472, name = "The Highlander's Will", classes = 1032, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Alliance",
              items = { 20060, 20046, 20053 } },
            { id = 483, name = "The Defiler's Determination", classes = 68, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Horde",
              items = { 20158, 20150, 20154 } },
            { id = 484, name = "The Defiler's Fortitude", classes = 68, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Horde",
              items = { 20203, 20195, 20199 } },
            { id = 485, name = "The Defiler's Intent", classes = 400, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Horde",
              items = { 20176, 20163, 20159 } },
            { id = 486, name = "The Defiler's Purpose", classes = 1032, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Horde",
              items = { 20194, 20190, 20186 } },
            { id = 487, name = "The Defiler's Resolution", classes = 3, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Horde",
              items = { 20212, 20204, 20208 } },
            { id = 488, name = "The Defiler's Will", classes = 1032, level = 65, quality = 4, label = "Arathi Basin", area = 3358, faction = "Horde",
              items = { 20175, 20171, 20167 } },
            { id = 443, name = "Bloodsoul Embrace", classes = 68, level = 65, quality = 3, label = "Blacksmithing", skill = 164,
              items = { 19691, 19690, 19692 } },
            { id = 444, name = "The Darksoul", classes = 3, level = 65, quality = 3, label = "Blacksmithing", skill = 164,
              items = { 19695, 19693, 19694 } },
            { id = 442, name = "Blood Tiger Harness", classes = 1032, level = 65, quality = 3, label = "Leatherworking", skill = 165,
              items = { 19689, 19688 } },
            { id = 441, name = "Primal Batskin", classes = 1032, level = 65, quality = 3, label = "Leatherworking", skill = 165,
              items = { 19685, 19687, 19686 } },
            { id = 421, name = "Bloodvine Garb", classes = 400, level = 65, quality = 3, label = "Tailoring", skill = 197,
              items = { 19682, 19683, 19684 } },
            { id = 476, name = "Augur's Regalia", classes = 64, level = 65, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19828, 19830, 19829, 19609, 19956 } },
            { id = 481, name = "Demoniac's Threads", classes = 256, level = 65, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19849, 20033, 19848, 19605, 19957 } },
            { id = 475, name = "Freethinker's Armor", classes = 2, level = 65, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19825, 19827, 19826, 19588, 19952 } },
            { id = 479, name = "Haruspex's Garb", classes = 1024, level = 65, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19838, 19840, 19839, 19613, 19955 } },
            { id = 482, name = "Illusionist's Attire", classes = 128, level = 65, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19845, 20034, 19846, 19601, 19959 } },
            { id = 478, name = "Madcap's Outfit", classes = 8, level = 65, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19835, 19834, 19836, 19617, 19954 } },
            { id = 474, name = "Vindicator's Battlegear", classes = 1, level = 65, quality = 4, label = "Zul'Gurub", area = 1977,
              items = { 19822, 19824, 19823, 19577, 19951 } },
            { id = 533, name = "Battlegear of Undead Slaying", classes = 3, level = 63, quality = 3, label = "Argent Dawn",
              items = { 23087, 23090, 23078 } },
            { id = 535, name = "Garb of the Undead Slayer", classes = 68, level = 63, quality = 3, label = "Argent Dawn",
              items = { 23088, 23092, 23082 } },
            { id = 536, name = "Regalia of Undead Cleansing", classes = 400, level = 63, quality = 3, label = "Argent Dawn",
              items = { 23085, 23091, 23084 } },
            { id = 534, name = "Undead Slayer's Armor", classes = 1032, level = 63, quality = 3, label = "Argent Dawn",
              items = { 23089, 23093, 23081 } },
            { id = 189, name = "Battlegear of Valor", classes = 1, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16731, 16733, 16730, 16735, 16737, 16736, 16732, 16734 } },
            { id = 186, name = "Beaststalker Armor", classes = 4, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16677, 16679, 16674, 16681, 16676, 16680, 16678, 16675 } },
            { id = 183, name = "Dreadmist Raiment", classes = 256, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16698, 16701, 16700, 16703, 16705, 16702, 16699, 16704 } },
            { id = 188, name = "Lightforge Armor", classes = 2, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16727, 16729, 16726, 16722, 16724, 16723, 16728, 16725 } },
            { id = 181, name = "Magister's Regalia", classes = 128, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16686, 16689, 16688, 16683, 16684, 16685, 16687, 16682 } },
            { id = 184, name = "Shadowcraft Armor", classes = 8, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16707, 16708, 16721, 16710, 16712, 16713, 16709, 16711 } },
            { id = 187, name = "The Elements", classes = 64, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16667, 16669, 16666, 16671, 16672, 16673, 16668, 16670 } },
            { id = 182, name = "Vestments of the Devout", classes = 16, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16693, 16695, 16690, 16697, 16692, 16696, 16694, 16691 } },
            { id = 185, name = "Wildheart Raiment", classes = 1024, level = 63, quality = 3, label = "Dungeon Set 1",
              items = { 16720, 16718, 16706, 16714, 16717, 16716, 16719, 16715 } },
            { id = 520, name = "Ironweave Battlesuit", classes = 400, level = 63, quality = 3, label = "Dungeons",
              items = { 22302, 22305, 22301, 22313, 22304, 22306, 22303, 22311 } },
            { id = 489, name = "Black Dragon Mail", classes = 68, level = 62, quality = 4, label = "Leatherworking", skill = 165,
              items = { 15051, 15050, 15052, 16984 } },
            { id = 142, name = "Stormshroud Armor", classes = 1032, level = 62, quality = 3, label = "Leatherworking", skill = 165,
              items = { 15058, 15056, 21278, 15057 } },
            { id = 321, name = "Imperial Plate", classes = 3, level = 61, quality = 2, label = "Blacksmithing", skill = 164,
              items = { 12427, 12428, 12422, 12425, 12424, 12429, 12426 } },
            { id = 141, name = "Volcanic Armor", classes = 1032, level = 61, quality = 2, label = "Leatherworking", skill = 165,
              items = { 15055, 15053, 15054 } },
            { id = 123, name = "Bloodmail Regalia", classes = 68, level = 61, quality = 3, label = "Scholomance", area = 2057,
              items = { 14611, 14615, 14614, 14612, 14616 } },
            { id = 121, name = "Cadaverous Garb", classes = 1032, level = 61, quality = 3, label = "Scholomance", area = 2057,
              items = { 14637, 14640, 14636, 14638, 14641 } },
            { id = 124, name = "Deathbone Guardian", classes = 3, level = 61, quality = 3, label = "Scholomance", area = 2057,
              items = { 14624, 14622, 14620, 14623, 14621 } },
            { id = 122, name = "Necropile Raiment", classes = 400, level = 61, quality = 3, label = "Scholomance", area = 2057,
              items = { 14633, 14626, 14629, 14632, 14631 } },
            { id = 81, name = "The Postmaster", classes = 400, level = 61, quality = 3, label = "Stratholme", area = 2017,
              items = { 13390, 13388, 13389, 13391, 13392 } },
            { id = 491, name = "Blue Dragon Mail", classes = 68, level = 60, quality = 3, label = "Leatherworking", skill = 165,
              items = { 15049, 15048, 20295 } },
            { id = 143, name = "Devilsaur Armor", classes = 1032, level = 60, quality = 3, label = "Leatherworking", skill = 165,
              items = { 15063, 15062 } },
            { id = 492, name = "Twilight Trappings", classes = 1503, level = 60, quality = 2, label = "Silithus", area = 1377,
              items = { 20408, 20406, 20407 } },
            { id = 144, name = "Ironfeather Armor", classes = 1032, level = 58, quality = 3, label = "Leatherworking", skill = 165,
              items = { 15067, 15066 } },
            { id = 1, name = "The Gladiator", classes = 68, level = 57, quality = 4, label = "Blackrock Depths", area = 1584,
              items = { 11729, 11726, 11730, 11728, 11731 } },
            { id = 490, name = "Green Dragon Mail", classes = 68, level = 56, quality = 3, label = "Leatherworking", skill = 165,
              items = { 15045, 20296, 15046 } },
            { id = 163, name = "Chain of the Scarlet Crusade", classes = 3, level = 43, quality = 3, label = "Scarlet Monastery", area = 796,
              items = { 10328, 10333, 10331, 10329, 10330, 10332 } },
            { id = 161, name = "Defias Leather", classes = 1100, level = 24, quality = 3, label = "The Deadmines", area = 1581,
              items = { 10399, 10401, 10403, 10400, 10402 } },
            { id = 162, name = "Embrace of the Viper", classes = 1100, level = 23, quality = 3, label = "Wailing Caverns", area = 718,
              items = { 6473, 10413, 10412, 10410, 10411 } },
        }

        self._byId, self._byItem = {}, {}
        for _, set in ipairs(self._sets) do
            self._byId[set.id] = set
            for _, item in ipairs(set.items) do
                local sets = self._byItem[item]
                if not sets then
                    sets = {}
                    self._byItem[item] = sets
                end
                sets[#sets + 1] = set
            end
        end
    end;
}
